---

- name: Lancement conteneur Apache
  hosts: prod
  become: true
  vars:
    packages: [wget, git]
  
  pre_tasks:
    - name: Recuperation pip
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: install pip
      command: python2.7 /tmp/get-pip.py
    - name: Install docker-python
      ansible.builtin.pip:
        name: docker-py
  
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_facts.distribution == "CentOs"

    - name: Create directory
      ansible.builtin.file:
        path: /homea/admin/files
        state: directory

    - name: Template site file
      ansible.builtin.template:
        src: ./templates/index.html.j2
        dest: /home/admin/files
      
    - name: Creation du conteneur
      community.docker.docker_container:
        name: apache_container
        image: httpd
        ports:
          - "80:80"
